### ISSUE TITLE
show secrets.py when appropriate

### ISSUE THREAD

**Issue by jepler** [circuitpython/CircuitPython_Library_Screenshot_Maker#6]
[this is not based on user feedback, just something that occurred to me]

I wonder whether the folder screenshots should show the `secrets.py` file (probably based on certain libraries, like requests, being installed)

.. this sort of speaks to the question of whether this shows what is  in the ZIP file or what is in the CIRCUITPY drive...

**Comment by FoamyGuy** [comment]
I think I had considered this at one point but didn't come up with a satisfactory way to know if it was required or not. Perhaps a list of "needs_secrets" libraries can be stored somewhere, but there are some libraries that could be optional. Like using the pyportal or magtag libraries but not for network things would not need a secrets.py file in order to work.

The original intent was to show the CIRCUITPY drive as it would look when running the project.

**Comment by FoamyGuy** [comment]
This is handled now ultimately with a list of libraries known to require `settings.toml` which gets added if any of these libraries are in use. https://github.com/circuitpython/CircuitPython_Library_Screenshot_Maker/blob/main/settings_required.py#L10
